"""Shared test configuration and fixtures for the db-cli test suite."""

import pytest

SAMPLE_VERSION = "2026.1.0.010"

VALID_DSBXML = f"""<?xml version="1.0" encoding="ISO-8859-15" standalone="yes"?>
<!--File generated by DesignBuilder-->
<dsbXML name="~Shoebox" date="2026-03-25" version="{SAMPLE_VERSION}" objects="all">
\t<Site handle="33" count="3">
\t\t<Attributes>
\t\t\t<Attribute name="WallConstr">0</Attribute>
\t\t</Attributes>
\t</Site>
</dsbXML>
"""

MALFORMED_XML = """<?xml version="1.0"?>
<dsbXML version="1.0">
\t<Site><Attributes></Site>
</dsbXML>
"""

WRONG_ROOT_XML = """<?xml version="1.0"?>
<NotDsbXML version="1.0"/>
"""


@pytest.fixture
def valid_xml(tmp_path):
    """A well-formed dsbXML file with a version attribute."""
    path = tmp_path / "Model.xml"
    path.write_text(VALID_DSBXML, encoding="iso-8859-15")
    return path


@pytest.fixture
def malformed_xml(tmp_path):
    """An XML file with mismatched tags."""
    path = tmp_path / "Broken.xml"
    path.write_text(MALFORMED_XML, encoding="utf-8")
    return path


@pytest.fixture
def wrong_root_xml(tmp_path):
    """A well-formed XML file whose root element is not dsbXML."""
    path = tmp_path / "Other.xml"
    path.write_text(WRONG_ROOT_XML, encoding="utf-8")
    return path
